server:
  port: 9090

spring:
  application:
    name: cg-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        # RUTA HACIA MICROSERVICIO DE CURSOS
        - id: cg-curso
          uri: lb://cg-curso
          predicates:
            - Path=/cursos/**,/alumnos/**
          filters:
            - AuthFilter

        - id: cg-matricula
          uri: lb://cg-matricula
          predicates:
            - Path=/matriculas/**

        - id: cg-auth
          uri: lb://cg-auth
          predicates:
            - Path=/auth/**

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}


#server:
#  port: 9090
#
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
#    instance:
#      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#
#
#spring:
#  application:
#    name: cg-gateway
#
#
#  cloud:
#    gateway:
#      server:
#        webflux:
#          discovery:
#            locator:
#              enabled: true
#              lower-case-service-id: true
#          routes:
#            - id: cg-curso
#              uri: lb://cg-curso
#              predicates:
#                - Path=/alumnos/**,/cursos/**
#              filters:
#                - AuthFilter
#
#            - id: cg-matricula
#              uri: lb://cg-matricula
#              predicates:
#                - Path=/matriculas/**
#
#            - id: cg-auth
#              uri: lb://cg-auth
#              predicates:
#                - Path=/auth/**
#







#server:
#  port: 9090
#
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8090/eureka
#  instance:
#    hostname: localhost
#
#
#spring:
#  application:
#    name: cg-gateway
#
#
#  cloud:
#    gateway:
#      server:
#        webflux:
#          discovery:
#            locator:
#              enabled: true
#              lower-case-service-id: true
#          routes:
#            - id: cg-curso
#              uri: lb://cg-curso
#              predicates:
#                - Path=/alumnos/**,/cursos/**
#
#
#            - id: cg-matricula
#              uri: lb://cg-matricula
#              predicates:
#                - Path=/matriculas/**

