server:
  port: 7070
spring:
  application:
    name: ms-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Toshibby/cg-colegio.git # ruta del repositorio git
          searchPaths: config-data
          default-label: circuitbreaker
  security:
    user:
      name: root
      password: 123456